<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8ce2da58fd2a5de764f46c4ade6ae4c5
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WPSDB\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WPSDB\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8ce2da58fd2a5de764f46c4ade6ae4c5::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8ce2da58fd2a5de764f46c4ade6ae4c5::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8ce2da58fd2a5de764f46c4ade6ae4c5::$classMap;

        }, null, ClassLoader::class);
    }
}
