<?php return array(
    'root' => array(
        'name' => 'jsongerber/wp-sync-db',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '3d5ad19fbb92c2495bc7e9f1991b3f5e8ad8a8ad',
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'jsongerber/wp-sync-db' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '3d5ad19fbb92c2495bc7e9f1991b3f5e8ad8a8ad',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-stubs/wordpress-globals' => array(
            'pretty_version' => 'v0.2.0',
            'version' => '0.2.0.0',
            'reference' => '748a1fb2ae8fda94844bd0545935095dbf404b32',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-stubs/wordpress-globals',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'php-stubs/wordpress-stubs' => array(
            'pretty_version' => 'v6.8.1',
            'version' => '6.8.1.0',
            'reference' => '92e444847d94f7c30f88c60004648f507688acd5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-stubs/wordpress-stubs',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'php-stubs/wp-cli-stubs' => array(
            'pretty_version' => 'v2.12.0',
            'version' => '2.12.0.0',
            'reference' => 'af16401e299a3fd2229bd0fa9a037638a4174a9d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-stubs/wp-cli-stubs',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
    ),
);
